FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
# Copy csproj and restore as distinct layers
COPY *.sln .
COPY src/Client/*.csproj ./src/Client/
COPY src/Common/*.csproj ./src/Common/
RUN dotnet restore ./src/Client/Client.csproj
# Copy everything else and build
COPY src/Client/. ./src/Client/
COPY src/Common/. ./src/Common/
WORKDIR /app/src/Client
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/src/Client/out ./
ENTRYPOINT ["dotnet", "Client.dll"]

