FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
# Copy csproj and restore as distinct layers
COPY *.sln .
COPY src/Worker/*.csproj ./src/Worker/
COPY src/Common/*.csproj ./src/Common/
RUN dotnet restore ./src/Worker/Worker.csproj
# Copy everything else and build
COPY src/Worker/. ./src/Worker/
COPY src/Common/. ./src/Common/
WORKDIR /app/src/Worker
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/src/Worker/out ./
ENTRYPOINT ["dotnet", "Worker.dll"]